sudo: required
language: go
services:
    - docker
go:
  - 1.7
  - master
install:
  - go get -v -t ./...
  - git --git-dir ../../docker/docker/.git checkout 667315576fac663bd80bbada4364413692e57ac6
script: sudo su -c "export GOPATH=$GOPATH; env; cd $TRAVIS_BUILD_DIR; pwd; go test -v ./..."
