sudo: required
language: go
services:
    - docker
go:
  - 1.7
  - master
install:
  - go get -t ./...
  - git --git-dir ../../docker/docker/.git checkout 667315576fac663bd80bbada4364413692e57ac6
script: go test -v ./...
